### ISSUE TITLE
Followups show requestor as the original person only

### ISSUE THREAD

**Issue by Kav-K** [Kav-K/GPTDiscord#186]
![image](https://user-images.githubusercontent.com/21161101/221695876-3db2f346-fd9b-4ed4-a45b-be8c235949e8.png)

Requestor of this follow up should've been me in this case

**Comment by Paillat-dev** [comment]
Wow that's old. Is it fixed or not?

**Comment by Kav-K** [comment]
hmm still not fixed I think @Paillat-dev
