### ISSUE TITLE
.txt support in conversations

### ISSUE THREAD

**Issue by cherryroots** [Kav-K/GPTDiscord#242]
Given the longer context limits gpt4 has and the current limitations we have surrounding the character limits of discord messages, we should let people upload .txt files, which can be read natively in discord by users so you can still read the conversation. 

The .txt files can be read in and added in it's entirety as the user's message, with whatever is in the text field and uploaded with the file being added before the file.
Example
![image](https://user-images.githubusercontent.com/15952522/226727892-2012e548-6850-4770-8097-cec5ca998739.png)
Would give the message content
```
Test\n\n{message.txt}
```

Doing this means we can avoid splitting messages up into multiple ones and feeding it to the bot one at a time.

There should probably be some sort of limit on the length of the file or we can run into the problem that the singular message in the history is bigger than the model can handle or saturates it too much, then no amount of embeddings will help. An option could be to split the contents into multiple chat entries instead so each one is smaller if it goes past a certain token amount depending on model context limits.

**Comment by Kav-K** [comment]
This should be implemented!

**Comment by ashra-academy** [comment]
I'm also needed this badly! is it implemented yet? my chat models can't seem to read attachment .txt files
