### ISSUE TITLE
Wolfram Step-by-step showcase

### ISSUE THREAD

**Issue by SunriseRedMoon** [Kav-K/GPTDiscord#265]
**Is your feature request related to a problem? Please describe.**
Cannot understand how certain calculation was reached. 

**Describe the solution you'd like**
If user has Wolfram Pro version, it will give responses with step-by-step explanation or how it got to the answer. 
[https://www.wolframalpha.com/pro/step-by-step-math-solver](https://www.wolframalpha.com/pro/step-by-step-math-solver)

**Comment by Kav-K** [comment]
Hmm, I need to find a way to get the API to return me the steps
