### ISSUE TITLE
Indication of usage of Wolfram API

### ISSUE THREAD

**Issue by Raecaug** [Kav-K/GPTDiscord#270]
**Describe the solution you'd like**
At present, it is not entirely clear when the bot has sourced information from Wolfram. 

As seen in your example, though the answer is given, there is no real indication that Wolfram's API was called.
![image](https://user-images.githubusercontent.com/23362597/232903824-c6804ce4-80ce-4190-ba08-d89ddfd936b0.png)

If some kind of indication could be given in the chat when the bot attempts to source info via Wolfram, this would be helpful for clarity.

**Comment by Kav-K** [comment]
Done! V11.4.1
