### ISSUE TITLE
[BUG] /internet prompt does not print to debug channel

### ISSUE THREAD

**Issue by Raecaug** [Kav-K/GPTDiscord#272]
**Describe the bug**
Prompts/messages from using `/internet chat` do not print in the debug channel.

**To Reproduce**
1. Use `/internet chat` and `/gpt converse` to prompt.
2. Debug messages will print for all prompts except internet chats.

**Comment by Kav-K** [comment]
hmm, the internet chats use a different pipeline than the regular chats, I wasn't planning on making this print debug prompts, do you need these?

**Comment by Raecaug** [comment]
It would be useful to have, for the sake of logging completeness; I do occasionally use the debug channel as a status indicator of bot usage when I'm away from easy access to the machine I host the bot on.
