### ISSUE TITLE
[ISSUE] Bot responds to system message and other bots' message

### ISSUE THREAD

**Issue by 0rangeAppl3** [Kav-K/GPTDiscord#288]
**Describe the bug**
in /index talk and / internet chat Bot responds to system message and other bots' message. Resulting in not able to change thread's name or generating irrelevant responses to other bots message.

**Expected behavior**
Bot should not responds to system message and other bots' message

**Screenshots**
![image](https://user-images.githubusercontent.com/14069364/234318310-0af8ff13-d4fb-46e2-89ac-fcba127e38e8.png)

**Comment by vigneshRamanathan3105** [comment]
@Kav-K  I am python intermediate and I would like to contribute to this issue with your guidance and this is would be my 1st open source contribution

**Comment by Kav-K** [comment]
Fixed!
