### ISSUE TITLE
Image generation or manipulation in /converse

### ISSUE THREAD

**Issue by whisperdrive** [Kav-K/GPTDiscord#292]
Currently, we are able to upload a picture to /converse and able to ask questions about the picture using natural language as though a real person. that's an excellent feature and worked really well.

I think the natural progression to this is the ability to use natural language to instruct the bot (just by using natural language) to generate an image. 

A further extension to this is the ability for for the user to use natural language to suggest changes to the generated (or uploaded) picture. 

Request: Nice to have

**Comment by Kav-K** [comment]
Hmm, maybe instead this may be better implemented in something like a /draw chat?
