### ISSUE TITLE
Discord User ID & DM Support

### ISSUE THREAD

**Issue by Maclean-D** [Kav-K/GPTDiscord#299]
The ability to DM the bot would be helpful in addition to just being able to message it on a server. Instead of a server ID, you could add a user ID. On that note, if you could add one user ID as having all features without needing roles that would simplify the process.

**Comment by Kav-K** [comment]
Roadmapped! But this isn't something that I'll be personally implementing in the near future so it would be great if someone could pick it up

**Comment by Kav-K** [comment]
Decided not to proceed with this due to security concerns and visibility of usage
