### ISSUE TITLE
Add Undetectable AI API Support

### ISSUE THREAD

**Issue by Maclean-D** [Kav-K/GPTDiscord#301]
Add the option to rewrite messages through [Undetectable AI](https://undetectable.ai?fpr=yws1m) with a context menu.

[I have created a bot that does this](https://github.com/Maclean-D/UndectableAIDicord) and we could just use that code here lol.

**Comment by Kav-K** [comment]
I won't be adding support for this, there is no such thing as an AI content detector until OpenAI incorporates a watermark into their generated output and institutions that flag students as detected AI writing are uneducated

**Comment by Kav-K** [comment]
I'd be open to a PR tho!

**Comment by Maclean-D** [comment]
Ok, I'll look into a PR. Most institutions are uneducated, but turnitin.com will check for AI-generated content automatically (https://www.turnitin.com/solutions/ai-writing), and some teachers will run things through GPTZero. Outside of institutions, it has other benefits because it generally makes things shorter and is good for businesses that want to use AI content.
