### ISSUE TITLE
[BUG] Continuous timeout during index query

### ISSUE THREAD

**Issue by odtest09** [Kav-K/GPTDiscord#305]
**Describe the bug**
Continuous timeout when doing index query. OpenAi charged token but in discord the bot never respond.
Docker log produce multiple entry as follow

WARNING:langchain.chat_models.openai:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60).

**Comment by Kav-K** [comment]
This is document specific and api latency specific, without more details unfortunately I can't investigate further. Provide me the file in another issue and Ill look into it
