### ISSUE TITLE
System instruction setting guide

### ISSUE THREAD

**Issue by Raecaug** [Kav-K/GPTDiscord#306]
I've noticed that `/gpt instruction` command doesn't have a guide on proper usage. @Hikari-Haru would you be able to give me the points of how it works, I'd be happy to add it to the docs?

**Comment by Hikari-Haru** [comment]
The commands lets you set a system instruction for turbo and gpt4, or just prepending text for davinci and older
The instruction will be added but not shown in the output not to be visually distracting
Instructions are persistent

The command has 3 options, `set` and `clear` can only be used with the `channel` type if the user has the `CHANNEL_INSTRUCTION_ROLES` role
- set
  - Lets you set an instruction for yourself with `user` or the channel with `channel`
  - `instruction` lets you set the text normally
  - `instruction_file` lets you upload a file which the text will be taken from and set as the instruction
  - When using both `instruction` and `instruction_file` they will be combined together with the `instruction` being added after the `instruction_file`
- get
  - prints out your instruction with `user` or the channel's instruction with `channel`
- clear
  - removes the instruction for the `user` who runs it or `channel` it's ran in.
 
Currently the user set instruction takes priority, then the channel instruction.
`Added user instruction to prompt` or `Added channel instruction to prompt` will be added before the output to indicate to the user that extra text has been added that's not shown

This applies to the `/gpt ask` command, @ the bot, and the right click context options

When used with davinci 3 or older models the spacing before the prompt and output is a bit ugly

**Comment by Raecaug** [comment]
Fixed in #309
