### ISSUE TITLE
[BUG] encode error in gpt ask

### ISSUE THREAD

**Issue by liulfy** [Kav-K/GPTDiscord#311]
![image](https://github.com/Kav-K/GPTDiscord/assets/27479464/a4bfbb89-0bfa-4a9c-862e-21673f2d7d5f)
when I use apt ask prompt_file, I upload excel or pdf file, it will raise the error. Could you please help deal with this problem?

**Comment by Kav-K** [comment]
You cannot use excel or PDF files with prompt_file, only text file
