### ISSUE TITLE
Add environment variable to disable ShareGPT

### ISSUE THREAD

**Issue by jeffe** [Kav-K/GPTDiscord#314]
**Is your feature request related to a problem? Please describe.**
In its current implementation content is always shared with a 3rd party service (shareGPT). 

**Describe the solution you'd like**
The ability to define a variable in .env to enable or disable sending any content to shareGPT

**Describe alternatives you've considered**
None. 

**Additional context**
Sending all content to shareGPT adds potential risk of information disclosure to a third party, and in its current state there is no simple solution for the bot host to determine whether or not they are ok with that risk.

**Comment by Kav-K** [comment]
In our current implementation, data is only sent to ShareGPT if you click the Share button, all conversations are not by default sent to them https://github.com/Kav-K/GPTDiscord/blob/13d12078726f3a39bf26e13563fb9a2e4eaee308/cogs/text_service_cog.py#L1497
