### ISSUE TITLE
[BUG]  /index talk isn't functioning properly

### ISSUE THREAD

**Issue by AndrewsPanda** [Kav-K/GPTDiscord#319]
***Just wanted to say thank you for being awesome. You have made something truly amazing

/index talk isn't functioning properly

**To Reproduce**
1. /index add pickle.txt_5_19.json
2. /index talk user_index:pickle.txt_5_19.json
3. Thread is started
4. Communicating with the bot and the bot doesn't recognise there is an index.

**Expected behavior**
Talk to the talk like you would in a converse thread but resourcing the indexed file

I'm available in your discord server for any follow up questions - PandasauruxRex#7608

**Comment by Kav-K** [comment]
This should be fixed
