### ISSUE TITLE
[BUG] cannot import name 'url_quote' from 'werkzeug.urls' | WITH FIX!

### ISSUE THREAD

**Issue by dehlirious** [Kav-K/GPTDiscord#342]
**Describe the bug**
Fresh install, unable to run.
`ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/dist-packages/werkzeug/urls.py)`

**To Reproduce**
1. Ubuntu 22
2. Git clone the github project
3. https://github.com/Kav-K/GPTDiscord/blob/main/detailed_guides/INSTALLATION.md#install-system-packages-python
4. `python3.9 gpt3discord.py  `
5. `ImportError: cannot import name 'url_quote' from 'werkzeug.urls' `

OR 
1. `docker run -d --name gpt3discord -v env_file:/opt/gpt3discord/etc/environment -v /containers/gpt3discord:/data -v /containers/gpt3discord/share:/data/share ghcr.io/kav-k/gptdiscord:main-full  `

**Expected behavior**
The application should've concluded the "Retrieved the General and Moderations DB" step and proceeded to the next step, after startup, and ran successfully

**Additional context**
Tried with python3.9 & 3.10

Whole debug statement(this was from the docker version which used 3.10 for some reason but even using python3.9 non docker, identical in errors)
```Loading environment from .env
Loading environment from /opt/gpt3discord/etc/environment
Loading environment from None
Attempting to retrieve the settings DB
Retrieved the settings DB
Attempting to retrieve the General and Moderations DB
Retrieved the General and Moderations DB
Traceback (most recent call last):
  File "/opt/gpt3discord/bin/gpt3discord.py", line 24, in <module>
    from services.health_service import HealthService
  File "/usr/local/lib/python3.10/site-packages/services/health_service.py", line 4, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 5, in <module>
Attempting to retrieve the General and Moderations DB
    from .app import Flask as Flask
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
```

HERE is where the issue is, and a solution

 ```python3.9 -m pip show Werkzeug
Name: Werkzeug
Version: 3.0.0
```

So lets downgrade to minimum requirement
`flask 2.2.3 requires Werkzeug>=2.2.2`
So I did
`python3.9 -m pip install werkzeug==2.2.2`
And wouldn't ya know? it worked! I'd hope you guys can modify `requirements.txt` to avoid this in the future!

**Comment by mgunnin** [comment]
I literally just hit this issue. Thank you for the post!

**Comment by mgunnin** [comment]
Ok, when I ran 
`python3.9 -m pip install werkzeug==2.0.0`

It obviously didnt work since you noted that flask 2.2.3 required >= 2.2.2.

So just change to `python3.9 -m pip install werkzeug==2.2.2` and it works fine.

**Comment by dehlirious** [comment]
> Ok, when I ran 
> `python3.9 -m pip install werkzeug==2.0.0`
> 
> It obviously didnt work since you noted that flask 2.2.3 required >= 2.2.2.
> 
> So just change to `python3.9 -m pip install werkzeug==2.2.2` and it works fine.

I am so sorry, I meant 2.2.2! That's what I installed for it to work correctly, thanks for correcting it!

**Comment by dehlirious** [comment]
[This](https://github.com/Kav-K/GPTDiscord/commit/14a2382138988c8313f0a4069568e060ec23ef6a) seems to fix it.
