### ISSUE TITLE
[BUG] You don't have permission, list of roles is ['openai', 'gpt']

### ISSUE THREAD

**Issue by poodarchu** [Kav-K/GPTDiscord#405]
**Describe the bug**
After I successfully setup the bot on my laptop, I got "You don't have permission, list of roles is ['openai', 'gpt']" for each command I input.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Kav-K** [comment]
@poodarchu Hi there, you didn't change the roles in the environment file to match what you needed, please read the section of the README regarding environment file and roles, or create roles "gpt" or "openai" and give yourself that role

**Comment by poodarchu** [comment]
Is there any example? I checked the .env file but don't know how to modify accordingly.

**Comment by Paillat-dev** [comment]
> Is there any example? I checked the .env file but don't know how to modify accordingly.

You can see https://github.com/Kav-K/GPTDiscord/blob/main/detailed_guides/INSTALLATION.md
