### ISSUE TITLE
8k context limit for 16k models with .txt attachments

### ISSUE THREAD

**Issue by ashra-academy** [Kav-K/GPTDiscord#436]
I'm not able to give more than 8k tokens with a 16k or 128k gpt4-preview model.

<img width="501" alt="Screenshot 2023-11-26 at 3 29 37 PM" src="https://github.com/Kav-K/GPTDiscord/assets/15813444/d6b3f125-348f-4e7a-beac-5f78fcc857b2">

**Comment by Kav-K** [comment]
Looks like turbo-16k only has an 8k token limit for output so you'll need to use a gpt-4 model like 32k or 1106-preview

**Comment by Kav-K** [comment]
Did you try it on the bot on the server?

**Comment by ashra-academy** [comment]
the issue is the input token limit. I also tried it on the server bot with gpt-32k and same issue. 
<img width="680" alt="Screenshot 2023-11-27 at 11 44 40 AM" src="https://github.com/Kav-K/GPTDiscord/assets/15813444/90a3a5fa-aa0f-4353-97b2-cb618e15b586">

**Comment by Kav-K** [comment]
The file is just too big, I don't understand your issue here @ashra-academy

**Comment by ashra-academy** [comment]
yes, but this file is not over the token limit. it is about 12k. And the gpt4 (32k limit) in open ChatGPT can handle the same input. 
So this is clearly a bug in the bot.

<img width="1041" alt="image" src="https://github.com/Kav-K/GPTDiscord/assets/15813444/91be1369-891c-4c61-a158-9b400836a309">

**Comment by Kav-K** [comment]
@ashra-academy It is certainly not a bug in the bot, the bot summarization threshold is set to 5k. Your file is bigger than that so it won't work. I set the threshold to 100k, you can try again now with the bot on the server.

**Comment by ashra-academy** [comment]
oh I didn't know about such a threshold parameter. It probably better be above 128k since the latest gpt4-preview is that much. Also how can I set this parameter on my own bot?

**Comment by Kav-K** [comment]
Above 128k doesn't make sense as it would hit the token limit before even beginning to summarize and also leaves no space for the summary afterwards, so something like 110k is more reasonable, you can set it with /system settings summarize_threshold
