### ISSUE TITLE
Ability to translate system messages

### ISSUE THREAD

**Issue by UltraHQ** [Kav-K/GPTDiscord#441]
**Additional context**
Would love to be able to translate the bot and it's system messages.

**Comment by UltraHQ** [comment]
> Can you elaborate a bit more your request?

I mean this:

![image](https://github.com/Kav-K/GPTDiscord/assets/35925402/a34b4f30-c847-4a0d-8411-88d98e42df3c)

Basically all the buttons and system messages.

And being able to translate those

**Comment by Kav-K** [comment]
I don't have any planned support for multiple locales in the foreseeable future, sorry! I would support anyone that would like to try on a PR though
