### ISSUE TITLE
not sending answer when i used internet search [BUG] 

### ISSUE THREAD

**Issue by nitin0909** [Kav-K/GPTDiscord#444]
when i used internet search command it show these output An error occured while performing search: [Errno 2] No such file or directory: '/tmp/llama_index'

**Comment by Kav-K** [comment]
Your dependencies are not correctly installed

**Comment by Kav-K** [comment]
Reinstall all the requirements in `requirements.txt` within a new environment, and then try `pip show llama_index` and paste here what it shows if you're still having some issues
