### ISSUE TITLE
[BUG] Bot not responding to mentions in reply

### ISSUE THREAD

**Issue by jeffe** [Kav-K/GPTDiscord#446]
**Describe the bug**
Bot does not detect/respond to @ mentions in replies to itself

**To Reproduce**
Steps to reproduce the behaviour:
1. Set BOT_TAGGABLE=True in .env
2. Send message @ bot
3. When bot replies, click reply to message in discord. 

**Expected behaviour**
When the bot is mentioned (eg "I think today is Monday, right? @bot" or "@bot Is today Monday?" ) the bot replies as expected.

**Comment by Kav-K** [comment]
This is expected behavior. Bot tagging is stateless

**Comment by jeffe** [comment]
> This is expected behavior. Bot tagging is stateless

Understood, my point was not that the bot should maintain state as much as I think it should identify that it was tagged regardless of context.
Is the underlying rationale that if in a reply the bot is tagged, people might be confused that the answers aren't collated?

**Comment by Kav-K** [comment]
No just that generally the tagging feature was originally designed to be
stateless, we don't want it emulating a conversation if we have chains of
replies and etc, an actual conversation should be used in that case
