### ISSUE TITLE
[BUG] Taggable mentions overriding converse opener

### ISSUE THREAD

**Issue by jeffe** [Kav-K/GPTDiscord#447]
**Describe the bug**
During a GPT converse with a custom opener set, using an @mention of the bot reverts back to the default 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a /gpt converse with an opener or opener_file
2. Inside of the thread / conversation, send a message that begins with the taggable name (eg @bot I think today is Monday) 

**Expected behaviour**
Inside of a converse thread with a custom opener or opener_file the bot should reply in its proper context whether it is tagged or not

**Comment by Kav-K** [comment]
Currently the way we have it set up, the tagging system is entirely contextless and is an independent system from conversations. I will disable tagging within a conversation
