### ISSUE TITLE
Voice channel transcription as input and TTS output through the voice channel

### ISSUE THREAD

**Issue by noalear** [Kav-K/GPTDiscord#96]
I'd like to capture voice channel audio and transcribe it to text, which would be taken as an input to GPT3. The output of GPT3 would be put into a TTS AI voice generation tool, such as FakeYou, and then the output of that would be broadcast over voice. 

In this way you could speak to GPT and it would speak back like any other person in Discord. If using FakeYou, the voice would be selected in the settings. Since there are various limits (depending on purchased tier) to the durations of each audio clip generated by FakeYou, you would need to estimate the duration of the audio and break it into segments. 

It would be most ideal to have a settable word or phrase to trigger the statement being sent to GPT such a name or something like "GPT tell me".

**Comment by Kav-K** [comment]
Roadmapped!

**Comment by uberdude420** [comment]
hah i just suggested this not knowing it was in the works... i am SOOOOO STOKED ON THIS KIND OF IDEA. lol

**Comment by Jiankun-Huang** [comment]
Same

**Comment by Jiankun-Huang** [comment]
Here: https://github.com/shirayu/whispering

**Comment by Maclean-D** [comment]
I think you could use the Discord voice API to get streams of participants when they start speaking and send it to whisper. Then it could just speak through google voice.

**Comment by Kav-K** [comment]
This will be finished soon in a separate bot! I will link it in the GPTDiscord server
